# Generated by Django 4.0.6 on 2022-08-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0009_alter_stroypicture_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='title',
        ),
    ]
