# Generated by Django 4.0.6 on 2022-08-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_socialring_location_socialring_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialring',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
